Add Changes entry for #269
maxmind/libmaxminddb pull request #270
Opened 2021-07-01 21:08 UTC by oschwald

2021-07-02 16:42 UTC, horgh requested changes

2021-07-02 16:42 UTC, horgh commented on Changes.md
> +* When build with Visual Studio, you may now build a static runtime with
"When built"?

2021-07-06 17:30 UTC, oschwald commented on Changes.md
> +* When build with Visual Studio, you may now build a static runtime with
Thanks! I amended the original commit.

2021-07-06 21:10 UTC, horgh approved these changes

2021-07-06 21:10 UTC, merged