Do not set feature test macro in public header
maxmind/libmaxminddb pull request #320
Opened 2023-08-04 21:33 UTC by horgh

2023-08-07 20:47 UTC, oschwald requested changes
One optional improvement. This or even an internal header throughout might be a bit cleaner, but I don't have strong opinion.

Do you think we will need to update any of our extensions for this change? If so, we should be sure to release those before we release this.

2023-08-07 20:47 UTC, oschwald commented on t/bad_databases_t.c
> +#endif
It doesn't matter too much, but could we have just set these in `maxminddb_test_helper.h`?

2023-08-08 17:24 UTC, horgh commented on t/bad_databases_t.c
> +#endif
I think we could. The reason I didn't is the spec says we should be setting them prior to including any header. I suppose it is fine to do that though given it's test code!

2023-08-08 18:43 UTC, horgh commented
I tested the Python, PHP, and Perl extensions with this version of libmaxminddb installed. I ran the tests as shown in the GitHub test action for each. All ran without issue, so I think we're okay with the extensions as they are.

2023-08-08 18:47 UTC, horgh commented
Console output of the tests - https://gist.github.com/horgh/f6c8b7a5ba3b042fcccb4111481bf214

2023-08-08 21:21 UTC, oschwald approved these changes

2023-08-08 21:21 UTC, merged